# Generated by Django 4.2.5 on 2023-09-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryData',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productDescription', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('productQuantity', models.IntegerField()),
                ('category', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='hakiapp.categorydata')),
            ],
        ),
    ]
